### ISSUE TITLE
JS-Validation fails in 4.2.3.

### ISSUE THREAD

**Issue by mjpr263** [in2code-de/femanager#122] opened 2019-01-24 08:47 UTC
After updating the extension to version 4.2.3. users can not register anymore. For each field i get the validation-response "Field could not be validated". When i compare the sended parameters with the last version, nothing has changed.

My validation-part in TS looks like this:

                validation {
                    email >
                    username {
                        required = 1
                        uniqueInDb = 1
                        email = 1
                    }
                    password {
                        required = 1
                        min = 10
                        mustInclude = number,letter
                    }
                    password_repeat {
                        required = 1
                        sameAs = password
                    }
                    terms {
                        required = 1
                    }
                }

Are there some changes in validation?

**Comment by pm-sschreiber** [comment] 2019-01-24 09:01
I can confirm this issue.

My validation TS is even simpler:

```
plugin.tx_femanager {
  settings {
    new {
      validation {
        username.required = 0
        email.uniqueInDb = 1
        privacypolicy.required = 1 # custom field
      }
    }
  }
}
```

**Comment by sbusemann** [comment] 2019-01-24 15:02
This is a duplicate of #119 - fixed in develop branch

**Closed by sbusemann** 2019-01-24 15:02 UTC
