### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by rowild** [in2code-de/femanager#350] opened 2021-06-09 14:39 UTC
This error is shown in the BE, when clicking on the icon ("Modules section"):

"Return value of In2code\Femanager\Domain\Service\RatelimiterService::getTSFE() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned"

?

TYPO3 10.4.17, php 7.3 (ddev)
femanager 6.1, also femanager 6.2

**Comment by mic-ha** [comment] 2021-06-10 10:12
Same here
TYPO3 10.4.17, php 7.4 (ddev)
Downgrading to femanager 6.1.2 no problems (should be, because Ratelimiter is a new feature)

**Comment by sbusemann** [comment] 2021-06-10 13:02
Duplicate of #348

**Closed by sbusemann** 2021-06-10 13:02 UTC
