### ISSUE TITLE
Fields names with error not displayed

### ISSUE THREAD

**Issue by webian** [in2code-de/femanager#269] opened 2020-09-03 11:16 UTC
If there are errors in form fields the flash messages are displayed but sometimes the "field name" (the part of the message before the colon) is not displayed (only the error detail is) so the user doesn't know which field the error is referred to.

**Comment by sbusemann** [comment] 2021-07-03 12:23
Is this maybe related due to missing language labels (which is fixed now)? Can you provide a concrete example?

**Comment by sbusemann** [comment] 2021-07-14 13:16
I close this issue, as i can not reproduce it.

**Closed by sbusemann** 2021-07-14 13:16 UTC
Labels: status: not reproducible
