### ISSUE TITLE
Upload-Folder for Images - Error

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#136] opened 2019-02-10 11:40 UTC
hi,

i have a problem with the Image Upload in a other Folder!
i use not the default "fileadmin/upload/" Folder.
In the T3 BE i create a new Folder "id=2", the fileadmin has the "id=1"
(This is the local HereTheName/ directory. This storage mount the Websites.)

tx_femanager.settings.uploadFolder = HereTheName/Upload/

if i add a new image for user, after the save button is this error in frontend:
_Oops, an error occurred! File /HereTheName/Upload/test-image.jpg/ does not exist. More information regarding this error might be available online._ 

after i edit the uploadFolder in "fileadmin/upload/" it works perfect with a new image for a user.

maybe the ext. need the new default id=2 ?

thanks for help!

**Comment by MK-42** [comment] 2019-02-10 15:07
That is currently not supported. See #75 for a possible solution, maybe you having the need for this could speed up adding this feature though.

**Comment by sbusemann** [comment] 2019-05-27 06:49
duplicate of  #74 and #75

**Closed by sbusemann** 2019-05-27 06:49 UTC
