### ISSUE TITLE
Redirect after user-confirmation-mail don't work

### ISSUE THREAD

**Issue by mjpr263** [in2code-de/femanager#252] opened 2020-08-05 15:20 UTC
When configuring the Plugin with activated user-confirmation the redirect to a confirmation-page after user clicks the confirmation link in e-mail dont work.

I configured the Redirect:

                userConfirmationRedirect = TEXT
                userConfirmationRedirect {
                    typolink {
                        parameter = 242
                        returnLast = url
                        #linkAccessRestrictedPages = 1
                    }
                }

But after clicking on the link the user is redirected to the start-page.

In AbstractController.php:redirectByAction the $target-Variable is sent to the T3-URIBuilder, converting it to "int". On this point the variable includes a string (the redirect-page-url), so the uribuilder returns 0.
`$this->uriBuilder->setTargetPageUid((int)$target);`

Changing this to
`$this->uriBuilder->setTargetPageUid((int)$this->config[$action . '.'][$category . '.']['typolink.']['parameter']);`
(like it was in an older version of femanager), everything works fine.

femanager-Version 6.0.1
TYPO3-Version 10.4.6

**Comment by andre-spindler** [comment] 2020-08-20 08:13
I can confirm this issue.
We use typo3 10 with femanager in version 6.0.1 (6.1.0 iss broken due to the autowiring bug #256).
Also the redirect after sending the user confirmation mail fails because all redirects are handled by this wrapper function.

femanager-Version 6.0.1
TYPO3-Version 10.4.6

**Comment by andre-spindler** [comment] 2020-08-20 08:42
In current femanager 6.1.0 the int conversion is still there. Not changed yet.
But the solution of Matthias Pruy removes the stdWrap options from the link. If pageUids are set in the site config, you have to import them with `typolink.parameter.data = SITE:whatever`

**Comment by Moongazer** [comment] 2020-12-18 13:17
We run into the same issue. On top of that it seems, that the auto-login doesn't work in this case. But not 100% sure if its related.

If we redirect the user (by location header) to another own controller-action, the session-cookie is set propperly, the user is auto-loggedin and the flash-messages of Femanager are available (we grabbing them from the femanager queue context). But if we configure the redirect in TS like above, strangehow a session is created where the ses_anonymous flag is set (and contains a blob with the flash-messages). So the user can not see the restricted-page.

Probably the "real" header-location redirect is needed first to set the cookie in the frond-end? Is a session always first created as anonymous, and as soon the first access happens it becomes a user-session?

**Comment by Patta** [comment] 2021-01-20 12:39
I can confirm that with femanager 6.1.2 the redirect typoscript example is not working anymore.

Changing the user redirect (or admin if adminconfirmation) after profile creation from:
```
redirect = TEXT
redirect {
  typolink {
    parameter = 23
    returnLast = url
  }
}
```
to:
```
redirect = TEXT
redirect {
  value = 23
}
```
works.

**Comment by sbusemann** [comment] 2021-07-03 11:54
Should be fixed with latest release, please check it. I will reopen it, if it does not work

**Closed by sbusemann** 2021-07-03 11:54 UTC
Labels: status: resolved

**Comment by jeyhunr** [comment] 2022-03-22 10:16
@Patta that worked for me too. thanks!
