### ISSUE TITLE
New gender type

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#334] opened 2021-02-15 09:03 UTC
Actually there is only male and female as option for the field gender. A third option (various, german: divers) would be great. Thank you!

**Comment by grosswerner** [comment] 2021-05-04 08:43
According to experts, the Federal Constitutional Court's decision that people have the right to a third gender entry could result in an obligation for store operators to offer a third gender for selection in addition to the salutation "Ms." and "Mr.".

**Comment by sbusemann** [comment] 2021-06-10 20:10
duplicate of #150

**Closed by sbusemann** 2021-06-10 20:10 UTC
