### ISSUE TITLE
Captcha will not work in 5.1.1

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/femanager#188] opened 2019-10-08 09:48 UTC
Hi,
the captcha will not work in 5.1.1

By setting `plugin.tx_femanager.settings.new.settings.captcha.captcha = 1` the captcha will not be shown.
In the partial Captcha.html the CaptchaEnabledViewHelper is called by
`<f:if condition="{femanager:Misc.CaptchaEnabled(settings: settings)}">`.  The argument settings is refered as bool an defined as bool in the CaptchaEnabledViewHelper. So `empty($settings[$controllerName]['validation']['captcha']['captcha']` will not work.

By setting `<f:if condition="{femanager:Misc.CaptchaEnabled(settings: '{settings}')}">` and register settings as array, the condition will work.

But after all, the captcha-field will return "Field could not be validated".

**Comment by davide-alghi** [comment] 2019-11-12 15:01
Hi, I encountered the same problem.
I fixed showing, but, anyway, I cannot submit the form: captcha value is always wrong

here
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Classes/ViewHelpers/Misc/CaptchaEnabledViewHelper.php#L20

```settings``` is a boolean and here
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Classes/ViewHelpers/Misc/CaptchaEnabledViewHelper.php#L32

it's accessed as array

my fix (showing)

```PHP
    public function render()
    {
        // $settings = $this->arguments['settings'];
        $controllerName = strtolower($this->renderingContext->getControllerContext()->getRequest()->getControllerName());

        // return ExtensionManagementUtility::isLoaded('sr_freecap')
        //     && !empty($settings[$controllerName]['validation']['captcha']['captcha']);
        return ExtensionManagementUtility::isLoaded('sr_freecap')
            && $this->templateVariableContainer->getByPath('settings.' . $controllerName . '.validation.captcha.captcha');

    }
```

**Comment by davide-alghi** [comment] 2019-11-13 15:57
So I fixed (maybe :/ ) javascript validation too.

function isValidationSettingsDifferentToGlobalSettings() at
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Classes/Domain/Validator/ClientsideValidator.php#L82
**always return true** because compare 'required' !== 'captcha(1)'
'required' from
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Resources/Private/Partials/Fields/CaptchaField.html#L13
and 'captcha(1)' from
```CODE
plugin.tx_femanager {
  settings {
    new {
        ...
        captcha {
          captcha = 1
        }
        ...
      }
    }
  }
}
```

Furthermore I didn't find any function / case to validate captcha into Classes/Domain/Validator/ClientsideValidator.php
_____
### My fix

in 
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Resources/Private/Partials/Fields/CaptchaField.html#L13
replaced with (as for all other fields)
```HTML
	additionalAttributes="{femanager:Validation.FormValidationData(settings:settings,fieldName:'captcha')}"
```
in function
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Classes/Domain/Validator/ClientsideValidator.php#L80

added the case for captcha
```PHP
                case stristr($validationSetting, 'captcha('):
                    $wordRepository = ObjectUtility::getObjectManager()->get(\SJBR\SrFreecap\Domain\Repository\WordRepository::class);
                    $wordObject = $wordRepository->getWord();
                    $wordHash = $wordObject->getWordHash();
                    $userVal = md5(strtolower(utf8_decode($this->getValue())));
                    if ($wordHash !== $userVal) {
                        $this->addMessage('validationErrorCaptcha', 'captcha');
                        $this->isValid = false;
                    }
                    break;
```

moreover, since it was missing, I added the captcha field label in
https://github.com/in2code-de/femanager/blob/cf4e3e0e568b4212e87f606756adfb998df718bb/Resources/Private/Language/locallang.xlf#L84
```HTML
			<trans-unit id="tx_femanager_domain_model_user.captcha">
				<source>Captcha</source>
			</trans-unit>
```

**Comment by Germar** [comment] 2019-11-29 22:46
I can confirm the fix will work and filled a Pullrequest

**Comment by stephangrass** [comment] 2020-01-08 12:38
I can also confirm the fix.

**Comment by lorddoumer** [comment] 2020-02-12 10:55
working for me too, thanks for the fix! hopefully it'll get merged soon.

**Comment by Hobokens** [comment] 2020-02-19 12:53
I can also confirm the fix.

**Comment by Germar** [comment] 2020-02-19 19:10
@lorddoumer for femanager 5.2 and sc_freecap 2.5 you also need [this patch](https://gist.github.com/Germar/41fa500983417ae1c519b7cc34e8f759)

**Comment by lorddoumer** [comment] 2020-02-20 10:53
@Germar thanks for your reply - I've started from scratch and reapplied both your patches for femaanger (2.5.0) and sc_freecap (2.5.3) but still doesn't work for me :-(

**Comment by rintisch** [comment] 2020-06-29 05:51
@Germar Thanks for this patch. Works for me. 

Hint if it might not work: I forgot to remove the language settings from my TypoScript (`config.sys_language_uid = 1`). That was the reason why the image was not rendered because it failed with `Call to a member function getPageOverlay() on string` (which was written into the log file).

**Comment by sbusemann** [comment] 2020-08-06 18:16
resolved in 6.x Branch (develop) and release as 5.3.1 for typo3 8.7 / 9.5

**Closed by sbusemann** 2020-08-06 18:16 UTC
