### ISSUE TITLE
TYPO3 11 femanager sr_freecap Validation error

### ISSUE THREAD

**Issue by sztop** [in2code-de/femanager#443] opened 2022-08-20 20:57 UTC
Hi, I installed femanager 7.0.0 inside of a TYPO3 11 instance and added sr_freecap 11.5.1. After activating the captcha plugin with typoscript it is shown properly at the end of femanagers registration form.
But the validation always shows an error when filling in the correct value ("Wrong captcha code"). This error occurs as well with JavaScript- as server-side-validation. Is this a common problem with TYPO3 11.5 because I haven't had this behaviour in older TYPO3 versions.
Thanks in advance for your help :)

Best wishes
Andreas

**Comment by milenishte** [comment] 2022-09-18 14:02
It happens to me too. I also tried to insert the element it in the template as per the documentation:
<f:render partial="CaptchaElement" />
and then validate with \SJBR\SrFreecap\Validation\Validator\CaptchaValidator in the controller, but still no success.
The image shows, but the validation always fails.

**Comment by vertexvaar** [comment] 2022-09-20 07:17
Hi @sztop 

i can not reproduce what you've reported in a freshly setup environment (TYPO3 11.5.16, femanager 7.0.0, sr_freecap 11.5.1, PHP 7.4, jQuery jquery-3.6.1.min.js). Can you please provide a reproducible minimal setup for this problem? (Maybe as zipped DDEV project including the DB dump), or as step by step instructions.

**Comment by Cleee** [comment] 2022-09-29 09:29
I Have the same problem with 

Typo3 11.5.9
sr_freecap 11.5.1
PHP 7.4
jquery 3.6.1

if you still cant reproduce i can try to send you an setup

**Comment by vertexvaar** [comment] 2022-09-29 13:34
> if you still cant reproduce i can try to send you an setup

Yes, please.

**Comment by vertexvaar** [comment] 2022-10-06 11:30
I found a way to reproduce the issue. It seems that the `fe_typo_user` cookie is not to set before the form was loaded.
@Cleee @sztop @milenishte can you confirm this?

**Comment by sztop** [comment] 2022-10-06 13:04
> It seems that the `fe_typo_user` cookie is not to set

Hm, I thought this cookie would only be set when an FE user is already logged in. In case of the registration form the user isn't logged in yet when filling out the form.

**Comment by Cleee** [comment] 2022-10-07 11:26
@vertexvaar Yes i can confirm that!!

Thats exactly the reason why its not working. If anyone got a workarround for that, please let me know!

**Comment by milenishte** [comment] 2022-10-07 14:05
@vertexvaar The cookie fe_typo_user is not set, yes.
I also made a test to submit my form as a logged user (this cookie was set when I logged in), but the captcha is still not validated successfully.

**Comment by Cleee** [comment] 2022-10-20 10:26
Does anyone got a good workarround?

I thought it is just checking if the fe_typo_user cookie is set, but i still got the same error if i set a fe_typo_user cookie with a random value like "not_logged_in" for users on registration pages which aren't logged in.

**Comment by vertexvaar** [comment] 2022-10-28 08:33
My colleague @pixeldesu forked and fixed the issue in sr-freecap. You can find the fork here: https://github.com/in2code-de/sr-freecap/tree/bugfix/wrong-captcha
I could confirm that the fork works as expected and fixes this issue, so im closing it.

**Closed by vertexvaar** 2022-10-28 08:33 UTC
Labels: status: planned
